version: "3.9"

services:
  scraper:
    container_name: scraper
    image: registry.digitalocean.com/pirata/scraper:latest
    env_file:
      - services/scraper/.env
    volumes:
      - type: bind
        source: ./services/scraper/pirata.db
        target: /app/pirata.db
    depends_on:
      - imdb
  imdb:
    container_name: imdb
    image: registry.digitalocean.com/pirata/imdb:latest
  prometheus:
    container_name: prometheus
    build: services/prometheus
    ports:
      - "9090:9090"
  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
  api:
    container_name: api
    build: services/api
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ./services/scraper/pirata.db
        target: /app/pirata.db
    depends_on:
      - imdb