version: "3.9"

services:
  scraper:
    container_name: scraper
    build: services/scraper
    env_file:
      - services/scraper/.env
  prometheus:
    container_name: prometheus
    build: services/prometheus
    network_mode: host
  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    network_mode: host
