# Note that make with no arguments executes the first rule in the file.
# command: requirements delimited by comma, also there requirements might be files

all: build

build:
	CGO_ENABLED=0 go build -o pirata_api .

